### ISSUE TITLE
Implement TheGraph subgraph for AssetPool event data.

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#137]
We need to define a subgraph for our asset pool smart contracts. Those contracts are deployed at an address and from this address events are stored on chain. 

Querying these events is a time consuming operation and TheGraph is a service that indexes this data decentralised in a decentralized way so we can access it easily from our API controllers.

As a POC it would be good to be able to query for the `MemberAddressChanged` event, since we need check for this one on every GET /members/:address call and a response will be slow when  a pool exists for a long time (there are a lot of blocks to check).

**Tasks**
- [ ] Figure out how to run TheGraph locally
- [ ]  Define subgraph for asset pools and MemberAddressChanged event
- [ ]  Create and deploy subgraph locally
- [ ]  Query locally to read event data

**Comment by bram-rongen** [comment]
We've decided to not pursue implementation of The Graph for now. Current usecases can be solved differently and adding The Graph to development and CI cycles are quite costly next to immediate implementation costs.
